name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    env:
      TEST: ""
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: |
        echo "Hello World" $AWS_REGION ${{ env.AWS_REGION }}
        echo 'TEST="Hello me"' >>$GITHUB_ENV
        aws --version
    - name: List Repo files
      run: echo $TEST
  
    
