name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
    - name: Hello World
      run: 'echo "Hello World" $AWS_REGION ${{ vars.AWS_REGION }}'
    - name: List Repo files
      run: ls -l
  
    
